name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      env:
        CI: true
      run: npm run test
    - name: Report
      if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        CI: true
        COVERALLS_GIT_BRANCH: ${{ github.ref }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: npm run test-ci
    - name: Build
      run: npm run build
    - name: Deploy
      if: github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run release
